# Kafka configuration
# Non-sensitive settings only - secrets should be loaded from environment variables
# Secrets (loaded from env):
#   - KAFKA_SCHEMA_REGISTRY_USERNAME
#   - KAFKA_SCHEMA_REGISTRY_PASSWORD
#   - KAFKA_TLS_CERT_FILE
#   - KAFKA_TLS_KEY_FILE
#   - KAFKA_TLS_CA_FILE

brokers:
  - "localhost:9092"

producer:
  required_acks: "all"
  batch_size: 1048576
  linger_ms: 10
  compression: "gzip"
  max_attempts: 10
  async: false
  commit_interval_ms: 1000
  max_message_size: 1048576
  partition_strategy: "hash"

consumer:
  min_bytes: 1024
  max_bytes: 10485760
  commit_interval_ms: 1000
  max_poll_records: 500
  heartbeat_interval_ms: 3000
  session_timeout_ms: 10000
  watch_partition_changes: true
  start_offset: "latest"

retry:
  max_retries: 3
  initial_backoff_ms: 100
  max_backoff_ms: 1000
  dlq_enabled: true
  dlq_topic_prefix: ".dlq"
  short_retry_attempts: 3
  max_long_retry_attempts: 3
  retry_topic_suffix: ".retry"

pool:
  max_connections: 10
  idle_timeout_seconds: 300

idempotency:
  enabled: true
  window_size_seconds: 300
  max_cache_size: 10000

security:
  enabled: false

schema_registry:
  enabled: false
  url: ""
  format: "avro"
  cache_ttl_seconds: 3600

transaction:
  enabled: false
  timeout_seconds: 60
  max_retries: 3
  retry_backoff_ms: 100
