run:
  timeout: 5m
  concurrency: 4
  allow-parallel-runners: true

linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unused
  disable:
    - depguard

linters-settings:
  revive:
    ignore-generated-header: true

issues:
  exclude-dirs:
    - internal/db/generated
    - api
    - vendor
  exclude-files:
    - ".*\\.gen\\.go$"
    - "mock_.*\\.go"
  max-issues-per-linter: 50
  max-same-issues: 3

output:
  print-issued-lines: true
  print-linter-name: true
