run:
  timeout: 5m
  tests: true
  modules-download-mode: vendor

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - gofmt
    - goimports
    - misspell
    - lll
    - unconvert
    - goconst
    - gocritic
    - prealloc

  disable:
    - exhaustivestruct

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  lll:
    line-length: 120
    tab-width: 4

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G104

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - sloppyReassign
